#配置数据源
spring:
  datasource:
     url: jdbc:mysql://www.xddal.com:3306/optimal
     username: root
     password: xd123456
     driver-class-name: com.mysql.cj.jdbc.Driver

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
